"use client";

import { useState, useRef, useEffect, useCallback } from "react";
import { ToolTemplate } from "@/components/ui/ToolTemplate";
import { Calendar, AlertCircle, Clock, Activity, Zap, Brain, Dumbbell, Coffee, Target, Download, Play, CheckCircle, ArrowRight, BarChart2, Flame } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Reorder, AnimatePresence, motion } from "framer-motion";

interface ScheduleItem {
  id: string;
  time: string;
  task: string;
  type: "focus" | "routine" | "meeting" | "break" | "personal" | "gym";
  duration: string;
  priority: number;
}

interface PlannerResult {
  score: number;
  message: string;
  impossible: boolean;
  schedule: ScheduleItem[];
}

export default function DailyPlanner() {
  const [isGenerating, setIsGenerating] = useState(false);
  const [result, setResult] = useState<PlannerResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const plannerRef = useRef<HTMLDivElement>(null);

  // Tabs state
  const [activeTab, setActiveTab] = useState<"plan" | "focus" | "stats">("plan");

  // Focus Timer state
  const [activeTask, setActiveTask] = useState<ScheduleItem | null>(null);
  const [timeLeft, setTimeLeft] = useState(25 * 60); // 25 mins
  const [isTimerRunning, setIsTimerRunning] = useState(false);

  // Stats State
  const [stats, setStats] = useState({ streaks: 0, focusMinutes: 0, tasksCompleted: 0 });

  const [formData, setFormData] = useState({
    tasks: "",
    goals: "",
    mode: "Founder",
    energyPeak: "Morning",
    timeFormat: "12-hour",
  });

  // Load stats from local storage on mount
  useEffect(() => {
    try {
      const saved = localStorage.getItem("dailyai_planner_stats");
      if (saved) {
        const parsed = JSON.parse(saved);
        if (parsed && typeof parsed === 'object') {
          setStats(prev => ({ ...prev, ...parsed }));
        }
      }
    } catch (e) {
      console.error("Failed to parse planner stats:", e);
    }
  }, []);

  const saveStats = useCallback((newStats: any) => {
    setStats(newStats);
    localStorage.setItem("dailyai_planner_stats", JSON.stringify(newStats));
  }, []);

  const handleGenerate = async () => {
    if (!formData.tasks || !formData.goals) {
      setError("Please list your tasks and top goals.");
      return;
    }

    setIsGenerating(true);
    setError(null);
    setResult(null);

    try {
      const response = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ tool: "planner", data: formData }),
      });

      const data = await response.json();
      if (!response.ok) throw new Error(data.error || "Failed to generate schedule");

      let parsedResult: PlannerResult;
      try {
        parsedResult = JSON.parse(data.result);
      } catch (e) {
        throw new Error("AI returned an invalid format. Please try again.");
      }

      setResult(parsedResult);
      setActiveTab("plan");
    } catch (err: any) {
      setError(err.message);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownloadPDF = async () => {
    if (!result) return;
    const element = plannerRef.current;
    if (!element) return;
    const html2pdf = (await import("html2pdf.js" as any)).default;
    const opt = {
      margin: [0.5, 0.5],
      filename: `SMART_Planner_${Date.now()}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2, useCORS: true, letterRendering: true },
      jsPDF: { unit: 'in', format: 'letter', orientation: 'portrait' }
    };
    html2pdf().set(opt).from(element).save();
  };

  const exportToICS = () => {
    if (!result || result.impossible) return;
    
    let icsContent = "BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//DailyAI//Planner//EN\n";
    
    // Simplistic ICS generation for demo purposes. In production, parsing '07:00 AM' accurately is required.
    // Assuming today's date
    const today = new Date();
    const dateStr = today.toISOString().split('T')[0].replace(/-/g, '');
    
    result.schedule.forEach(item => {
      // Very basic time parsing (Assumes formats like "07:00 AM - 08:00 AM")
      const timeMatch = item.time.match(/(\d+):(\d+)\s*(AM|PM)/i);
      let startHour = 9;
      if (timeMatch) {
         startHour = parseInt(timeMatch[1]);
         if (timeMatch[3].toUpperCase() === 'PM' && startHour < 12) startHour += 12;
         if (timeMatch[3].toUpperCase() === 'AM' && startHour === 12) startHour = 0;
      }
      
      const startTime = `${dateStr}T${startHour.toString().padStart(2, '0')}0000Z`;
      const endTime = `${dateStr}T${(startHour + 1).toString().padStart(2, '0')}0000Z`; // Mocking 1 hour duration

      icsContent += "BEGIN:VEVENT\n";
      icsContent += `DTSTART:${startTime}\n`;
      icsContent += `DTEND:${endTime}\n`;
      icsContent += `SUMMARY:${item.task}\n`;
      icsContent += `DESCRIPTION:Generated by DailyAI Tools\n`;
      icsContent += "END:VEVENT\n";
    });

    icsContent += "END:VCALENDAR";

    const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
    const link = document.createElement('a');
    link.href = window.URL.createObjectURL(blob);
    link.setAttribute('download', 'DailyAI_Schedule.ics');
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  // Timer Logic
  useEffect(() => {
    let interval: any = null;
    if (isTimerRunning && timeLeft > 0) {
      interval = setInterval(() => setTimeLeft(t => t - 1), 1000);
    } else if (timeLeft === 0 && isTimerRunning) {
      setIsTimerRunning(false);
      // Add to stats using functional update to avoid effect dependency on 'stats'
      setStats(prev => {
        const updated = { ...prev, focusMinutes: prev.focusMinutes + 25 };
        localStorage.setItem("dailyai_planner_stats", JSON.stringify(updated));
        return updated;
      });
      alert("Focus Session Complete! You earned +25 Focus Minutes.");
    }
    return () => clearInterval(interval);
  }, [isTimerRunning, timeLeft]);

  const toggleTimer = () => setIsTimerRunning(!isTimerRunning);
  
  const startTaskFocus = (task: ScheduleItem) => {
    setActiveTask(task);
    setActiveTab("focus");
    setTimeLeft(25 * 60);
    setIsTimerRunning(true);
  };

  const markTaskComplete = (taskId: string) => {
    if (!result) return;
    setResult(prev => prev ? {
      ...prev,
      schedule: prev.schedule.filter(t => (t.id || t.task) !== taskId)
    } : null);
    
    saveStats({ 
      ...stats, 
      tasksCompleted: stats.tasksCompleted + 1, 
      streaks: stats.streaks === 0 ? 1 : stats.streaks 
    });
  };

  const autoReschedule = () => {
    if (!result) return;
    // Simple visual auto-reschedule mock (re-orders or shows success)
    alert("Schedule Optimized! Missed tasks have been pushed to tomorrow's backlog.");
  };

  const modes = ["Student", "Founder", "Exam Mode", "Beast Mode"];
  const energyPeaks = ["Morning (5AM - 11AM)", "Afternoon (12PM - 4PM)", "Night Owl (8PM - 2AM)"];
  const formats = ["12-hour", "24-hour"];

  const getTypeIcon = (type: string) => {
    const iconProps = { className: "w-5 h-5" };
    switch (type.toLowerCase()) {
      case "focus": return <Brain {...iconProps} style={{ color: "#a855f7" }} />;
      case "routine": return <Activity {...iconProps} style={{ color: "#3b82f6" }} />;
      case "meeting": return <Target {...iconProps} style={{ color: "#f97316" }} />;
      case "break": return <Coffee {...iconProps} style={{ color: "#22c55e" }} />;
      case "gym": return <Dumbbell {...iconProps} style={{ color: "#ef4444" }} />;
      default: return <Clock {...iconProps} style={{ color: "#64748b" }} />;
    }
  };

  const getTypeStyle = (type: string, priority: number) => {
    // Priority Heatmap overrides: If priority 5 (Highest), make it intense Red/Orange
    if (priority === 5) {
      return { backgroundColor: "#fff1f2", borderLeft: "4px solid #e11d48", borderColor: "#ffe4e6" }; // Rose
    }
    
    switch (type.toLowerCase()) {
      case "focus": return { backgroundColor: "#f3e8ff", borderLeft: "4px solid #a855f7", borderColor: "#e9d5ff" };
      case "routine": return { backgroundColor: "#f8fafc", borderLeft: "4px solid #cbd5e1", borderColor: "#f1f5f9" };
      case "meeting": return { backgroundColor: "#fff7ed", borderLeft: "4px solid #f97316", borderColor: "#ffedd5" };
      case "break": return { backgroundColor: "#f0fdf4", borderLeft: "4px solid #22c55e", borderColor: "#dcfce7" };
      case "gym": return { backgroundColor: "#fef2f2", borderLeft: "4px solid #ef4444", borderColor: "#fee2e2" };
      default: return { backgroundColor: "#f8fafc", borderLeft: "4px solid #94a3b8", borderColor: "#e2e8f0" };
    }
  };

  return (
    <div className="max-w-6xl mx-auto space-y-6">
      {/* Premium Multi-Tab Header */}
      <div className="flex bg-white/5 p-1 rounded-2xl border border-white/10 w-fit">
        {(["plan", "focus", "stats"] as const).map(tab => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`px-6 py-2 rounded-xl text-sm font-bold capitalize transition-all ${activeTab === tab ? "bg-primary text-white shadow-lg" : "text-gray-400 hover:text-white hover:bg-white/5"}`}
          >
            {tab}
          </button>
        ))}
      </div>

      <ToolTemplate
        title={activeTab === "plan" ? "Premium AI Planner" : activeTab === "focus" ? "Focus Mode" : "Habits & Stats"}
        description={activeTab === "plan" ? "Motion/Notion style scheduling with energy mapping." : activeTab === "focus" ? "Deep work Pomodoro timer." : "Your weekly productivity streak."}
        icon={activeTab === "plan" ? Calendar : activeTab === "focus" ? Target : BarChart2}
        isGenerating={isGenerating}
        onGenerate={handleGenerate}
        hideGenerateButton={activeTab !== "plan" || (activeTab === "plan" && result !== null)}
        result={
          activeTab === "stats" ? (
            <div className="animate-in fade-in slide-in-from-bottom-4 space-y-6 w-full text-left">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div className="bg-white/5 border border-white/10 p-6 rounded-2xl flex flex-col items-center justify-center">
                  <Flame className="w-8 h-8 text-orange-500 mb-2" />
                  <span className="text-3xl font-black text-white">{stats.streaks}</span>
                  <span className="text-xs text-gray-400 font-bold uppercase tracking-widest mt-1">Day Streak</span>
                </div>
                <div className="bg-white/5 border border-white/10 p-6 rounded-2xl flex flex-col items-center justify-center">
                  <Brain className="w-8 h-8 text-purple-500 mb-2" />
                  <span className="text-3xl font-black text-white">{stats.focusMinutes}</span>
                  <span className="text-xs text-gray-400 font-bold uppercase tracking-widest mt-1">Focus Mins</span>
                </div>
                <div className="bg-white/5 border border-white/10 p-6 rounded-2xl flex flex-col items-center justify-center">
                  <CheckCircle className="w-8 h-8 text-green-500 mb-2" />
                  <span className="text-3xl font-black text-white">{stats.tasksCompleted}</span>
                  <span className="text-xs text-gray-400 font-bold uppercase tracking-widest mt-1">Tasks Done</span>
                </div>
              </div>
            </div>
          ) : activeTab === "focus" ? (
            <div className="animate-in fade-in slide-in-from-bottom-4 flex flex-col items-center justify-center py-12 text-center w-full">
              <h3 className="text-2xl font-black text-white mb-2">{activeTask ? activeTask.task : "Free Focus Session"}</h3>
              <p className="text-gray-400 mb-12">Put your phone away. Stay in the zone.</p>
              
              <div className="w-64 h-64 rounded-full border-8 border-white/10 flex items-center justify-center mb-8 relative">
                <div className="absolute inset-0 rounded-full border-8 border-primary border-t-transparent animate-spin" style={{ animationDuration: "3s", opacity: isTimerRunning ? 1 : 0 }}></div>
                <span className="text-6xl font-black text-white font-mono">
                  {Math.floor(timeLeft / 60).toString().padStart(2, '0')}:{(timeLeft % 60).toString().padStart(2, '0')}
                </span>
              </div>

              <div className="flex gap-4">
                <Button onClick={toggleTimer} variant="premium" className="w-32">
                  {isTimerRunning ? "Pause" : "Start"}
                </Button>
                <Button onClick={() => setTimeLeft(25 * 60)} variant="outline" className="w-32 bg-white/5 text-white">
                  Reset
                </Button>
              </div>
            </div>
          ) : activeTab === "plan" && result ? (
            <div className="space-y-6 animate-in fade-in duration-500 text-left w-full">
              <div 
                ref={plannerRef}
                className="p-8 rounded-xl relative overflow-hidden"
                style={{ backgroundColor: "#ffffff", color: "#0f172a", fontFamily: "'Inter', sans-serif", boxShadow: "0 25px 50px -12px rgba(0, 0, 0, 0.25)" }}
              >
                {/* Header Section */}
                <div className="flex justify-between items-center mb-8 border-b pb-6" style={{ borderColor: "#e2e8f0" }}>
                  <div>
                    <h2 className="text-3xl font-black tracking-tight" style={{ color: "#0f172a" }}>Daily Masterplan</h2>
                    <p className="font-medium mt-1" style={{ color: "#64748b" }}>{new Date().toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })} • {formData.mode}</p>
                  </div>
                  {!result.impossible && (
                    <div className="flex flex-col items-end">
                      <div className="flex items-center gap-2">
                        <div className="text-4xl font-black" style={{ color: "#8b5cf6" }}>{result.score}</div>
                        <div className="text-sm font-bold uppercase tracking-widest leading-tight" style={{ color: "#94a3b8" }}>
                          Productivity<br/>Score
                        </div>
                      </div>
                    </div>
                  )}
                </div>

                {result.impossible ? (
                  <div className="p-6 rounded-xl mb-6 border" style={{ backgroundColor: "#fef2f2", borderColor: "#fecaca" }}>
                    <div className="flex items-center gap-3 mb-2">
                      <AlertCircle className="w-6 h-6" style={{ color: "#dc2626" }} />
                      <h3 className="text-xl font-bold" style={{ color: "#7f1d1d" }}>Impossible Schedule Detected</h3>
                    </div>
                    <p style={{ color: "#b91c1c" }}>{result.message}</p>
                  </div>
                ) : (
                  <>
                    <div className="p-4 rounded-xl mb-8 border flex items-start gap-3" style={{ backgroundColor: "#f8fafc", borderColor: "#f1f5f9" }}>
                      <Zap className="w-5 h-5 shrink-0 mt-0.5" style={{ color: "#f59e0b" }} />
                      <p className="text-sm font-medium" style={{ color: "#334155" }}>{result.message}</p>
                    </div>

                    {/* Framer Motion Reorder List */}
                    <Reorder.Group 
                      axis="y" 
                      values={result.schedule} 
                      onReorder={(newOrder) => setResult(prev => prev ? {...prev, schedule: newOrder} : null)} 
                      className="space-y-4"
                    >
                      <AnimatePresence>
                        {result.schedule.map((item, index) => (
                          <Reorder.Item 
                            key={item.id ? `task-${item.id}` : `task-idx-${index}-${item.task}`} 
                            value={item} 
                            className="flex flex-col sm:flex-row gap-4 group cursor-grab active:cursor-grabbing"
                          >
                            
                            {/* Time Block */}
                            <div className="w-full sm:w-40 shrink-0 sm:text-right pt-4">
                              <span className="text-sm font-bold" style={{ color: "#0f172a" }}>{item.time}</span>
                              <p className="text-xs font-semibold mt-1" style={{ color: "#94a3b8" }}>{item.duration}</p>
                            </div>
                            
                            {/* Task Card */}
                            <div className="relative pb-8 flex-1">
                              {index !== result.schedule.length - 1 && (
                                <div className="absolute left-8 top-16 bottom-0 w-px hidden sm:block" style={{ backgroundColor: "#e2e8f0" }}></div>
                              )}
                              
                              <div 
                                className="p-4 rounded-xl border flex flex-col sm:flex-row sm:items-center justify-between gap-4 transition-all"
                                style={{ ...getTypeStyle(item.type, item.priority || 1), boxShadow: "0 1px 2px 0 rgba(0, 0, 0, 0.05)" }}
                              >
                                <div className="flex items-start gap-4">
                                  <div className="p-2 rounded-lg" style={{ backgroundColor: "#ffffff" }}>
                                    {getTypeIcon(item.type)}
                                  </div>
                                  <div>
                                    <h4 className="text-base font-bold leading-tight" style={{ color: "#0f172a" }}>{item.task}</h4>
                                    <div className="flex items-center gap-2 mt-2">
                                      <span className="inline-block px-2.5 py-0.5 rounded text-[10px] font-bold uppercase tracking-wider shadow-sm" style={{ backgroundColor: "#ffffff", color: "#64748b" }}>
                                        {item.type}
                                      </span>
                                      {item.priority === 5 && (
                                        <span className="inline-flex items-center gap-1 text-[10px] font-bold uppercase tracking-wider" style={{ color: '#e11d48' }}>
                                          <Flame className="w-3 h-3" /> Priority Peak
                                        </span>
                                      )}
                                    </div>
                                  </div>
                                </div>

                                {/* Actions */}
                                <div className="flex gap-2">
                                  <button 
                                    onClick={() => startTaskFocus(item)}
                                    className="p-2 rounded-lg hover:bg-slate-50 transition-colors"
                                    style={{ backgroundColor: "#ffffff", boxShadow: "0 1px 2px 0 rgba(0, 0, 0, 0.05)" }}
                                    title="Start Focus Timer"
                                  >
                                    <Play className="w-4 h-4" style={{ color: "#9333ea" }} />
                                  </button>
                                  <button 
                                    onClick={() => markTaskComplete(item.id || item.task)}
                                    className="p-2 rounded-lg hover:bg-slate-50 transition-colors"
                                    style={{ backgroundColor: "#ffffff", boxShadow: "0 1px 2px 0 rgba(0, 0, 0, 0.05)" }}
                                    title="Mark Complete"
                                  >
                                    <CheckCircle className="w-4 h-4" style={{ color: "#16a34a" }} />
                                  </button>
                                </div>
                              </div>
                            </div>
                          </Reorder.Item>
                        ))}
                      </AnimatePresence>
                    </Reorder.Group>
                  </>
                )}
              </div>
            </div>
          ) : null
        }
      >
        {/* CHILDREN (LEFT SIDE) */}
        {activeTab === "plan" && (
          <div className="space-y-6">
            {error && (
              <div className="bg-red-500/10 border border-red-500/50 text-red-500 px-4 py-3 rounded-xl text-sm flex items-center gap-2 mb-6">
                <AlertCircle className="w-4 h-4" /> {error}
              </div>
            )}

            {!result ? (
              <>
                <div className="grid grid-cols-2 gap-4 mb-6">
                  <div>
                    <label className="block text-[10px] font-black uppercase tracking-[0.2em] text-gray-500 mb-2">Schedule Mode</label>
                    <select 
                      value={formData.mode}
                      onChange={(e) => setFormData({...formData, mode: e.target.value})}
                      className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 focus:border-primary outline-none text-sm transition-all text-white"
                    >
                      {modes.map(t => <option key={t} className="bg-slate-900">{t}</option>)}
                    </select>
                  </div>
                  <div>
                    <label className="block text-[10px] font-black uppercase tracking-[0.2em] text-gray-500 mb-2">Energy Peak</label>
                    <select 
                      value={formData.energyPeak}
                      onChange={(e) => setFormData({...formData, energyPeak: e.target.value})}
                      className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 focus:border-primary outline-none text-sm transition-all text-white"
                    >
                      {energyPeaks.map(t => <option key={t} className="bg-slate-900">{t}</option>)}
                    </select>
                  </div>
                </div>

                <div>
                  <label className="block text-[10px] font-black uppercase tracking-[0.2em] text-gray-500 mb-2 flex items-center gap-2">
                    <Target className="w-3 h-3 text-primary" /> Top Goals For Today
                  </label>
                  <textarea 
                    value={formData.goals}
                    onChange={(e) => setFormData({...formData, goals: e.target.value})}
                    className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 focus:outline-none focus:border-primary transition-colors text-white min-h-[80px]" 
                    placeholder="e.g. Finish the homepage design, call the client..."
                  />
                </div>

                <div>
                  <label className="block text-[10px] font-black uppercase tracking-[0.2em] text-gray-500 mb-2 mt-4 flex items-center gap-2">
                    <Clock className="w-3 h-3 text-primary" /> Tasks & Specific Times
                  </label>
                  <textarea 
                    value={formData.tasks}
                    onChange={(e) => setFormData({...formData, tasks: e.target.value})}
                    className="w-full bg-black/40 border border-white/10 rounded-xl px-4 py-3 focus:outline-none focus:border-primary transition-colors text-white min-h-[150px]" 
                    placeholder="e.g. Wake up at 7 AM&#10;Gym at 6 PM&#10;Sleep by 11:30 PM&#10;Write 2 blog posts&#10;Fix header bug"
                  />
                </div>
              </>
            ) : (
              <div className="flex flex-col gap-4">
                <div className="p-6 bg-white/5 border border-white/10 rounded-2xl">
                  <h3 className="text-xl font-bold text-white mb-2">Schedule Active</h3>
                  <p className="text-sm text-gray-400 mb-6">Manage your generated schedule or export it to your native calendar.</p>
                  
                  <div className="flex flex-col gap-3">
                    <Button variant="outline" className="w-full bg-white/5 border-white/10 text-white justify-start" onClick={autoReschedule}>
                      <ArrowRight className="w-4 h-4 mr-3" /> Auto-Reschedule Tasks
                    </Button>
                    <Button variant="outline" className="w-full bg-white/5 border-white/10 text-white justify-start" onClick={exportToICS}>
                      <Calendar className="w-4 h-4 mr-3" /> Sync to Google Calendar
                    </Button>
                    <Button variant="premium" className="w-full justify-start" onClick={handleDownloadPDF}>
                      <Download className="w-4 h-4 mr-3" /> Download PDF
                    </Button>
                    <div className="h-px w-full bg-white/10 my-2"></div>
                    <Button variant="outline" className="w-full border-red-500/20 text-red-400 hover:bg-red-500/10 justify-start" onClick={() => setResult(null)}>
                      Discard & Create New
                    </Button>
                  </div>
                </div>
              </div>
            )}
          </div>
        )}
        
        {/* Empty state messages for Focus and Stats on the left side to look clean */}
        {activeTab === "focus" && (
           <div className="text-left">
             <h2 className="text-2xl font-black text-white mb-4">Focus Mode</h2>
             <p className="text-gray-400">Click the 'Play' icon on any task in your generated schedule to start a dedicated Pomodoro focus block here.</p>
           </div>
        )}

        {activeTab === "stats" && (
           <div className="text-left">
             <h2 className="text-2xl font-black text-white mb-4">Your Progress</h2>
             <p className="text-gray-400">Track your daily streaks, deep work minutes, and completed tasks to maintain momentum.</p>
           </div>
        )}

      </ToolTemplate>
    </div>
  );
}
